### PR TITLE
[ENG-6679] Support debug testing on Android

### LINKED ISSUE #4: Android not working on development builds
i have one question.
does 'detox:android:debug:test' script work correctly?
i think it is hanging expo intro screen :(

when i run 'detox:android:debug:test' after 'detox:android:debug:build'
it couldn't run with this error logs

thanks for your effort

```
21:12:28.657 detox[59778] INFO:  Home screen is assigned to emulator-5554 (Pixel_4_API_31)
21:12:28.657 detox[59778] INFO:  Home screen: "Click me" button should be visible
21:14:28.681 detox[59778] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = 1) currentStatus: {}
  (id = -1000) isReady: {}

That might be the reason why the test "Home screen "Click me" button should be visible" has timed out.

21:14:28.682 detox[59778] INFO:  Home screen: "Click me" button should be visible [FAIL]
21:14:28.691 detox[59778] INFO:  Home screen: shows "Hi!" after tapping "Click me"
21:14:28.698 detox[59778] WARN:  at node_modules/detox/src/devices/runtime/drivers/android/AndroidDriver.js:156:17 
 An error occurred while waiting for the app to become ready. Waiting for disconnection... Error:
 DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
    at MonitoredInstrumentation._getInstrumentationCrashError (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js:72:12)
    at MonitoredInstrumentation._rejectPendingCrashPromise (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js:60:37)
    at MonitoredInstrumentation._onInstrumentationTerminated (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js:55:10)
    at Instrumentation._onTerminated (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/Instrumentation.js:54:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
21:14:28.752 detox[59778] WARN:  at node_modules/detox/src/devices/runtime/drivers/android/AndroidDriver.js:158:17 
 ...app disconnected.
21:16:28.699 detox[59778] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = 2) currentStatus: {}
  (id = -1000) isReady: {}

That might be the reason why the test "Home screen shows "Hi!" after tapping "Click me"" has timed out.

21:16:28.699 detox[59778] INFO:  Home screen: shows "Hi!" after tapping "Click me" [FAIL]

21:16:28.800 detox[59778] WARN:  at node_modules/detox/src/devices/runtime/drivers/android/AndroidDriver.js:156:17 
 An error occurred while waiting for the app to become ready. Waiting for disconnection... Error:
 DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
    at MonitoredInstrumentation._getInstrumentationCrashError (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js:72:12)
    at MonitoredInstrumentation._rejectPendingCrashPromise (/Users/.../eas-tests-.example/node_modules/detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js:60:37)
    at MonitoredInstrumentation._onInstrumentationTerminated (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js:55:10)
    at Instrumentation._onTerminated (/Users/.../eas-tests-example/node_modules/detox/src/devices/common/drivers/android/tools/Instrumentation.js:54:18)
21:16:28.800 detox[59778] WARN:  at node_modules/detox/src/devices/runtime/drivers/android/AndroidDriver.js:158:17 
 ...app disconnected.
 FAIL  e2e/tests/homeScreen.e2e.js (241.547 s)
  Home screen
    ✕ "Click me" button should be visible (120005 ms)
    ✕ shows "Hi!" after tapping "Click me" (120007 ms)

  ● Home screen › "Click me" button should be visible

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      2 |
      3 | describe('Home screen', () => {
    > 4 |   beforeEach(async () => {
        |   ^
      5 |     await device.launchApp({
      6 |       newInstance: true,
      7 |     });

      at beforeEach (tests/homeScreen.e2e.js:4:3)
      at Object.describe (tests/homeScreen.e2e.js:3:1)

  ● Home screen › shows "Hi!" after tapping "Click me"

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      2 |
      3 | describe('Home screen', () => {
    > 4 |   beforeEach(async () => {
        |   ^
      5 |     await device.launchApp({
      6 |       newInstance: true,
      7 |     });

      at beforeEach (tests/homeScreen.e2e.js:4:3)
      at Object.describe (tests/homeScreen.e2e.js:3:1)

21:16:29.051 detox[59777] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' e2e


Process finished with exit code 1

```

### PR DESCRIPTION
**Pull request by douglowder**
Fixes #4 .

- Follow the suggestion by @david-alza to modify the Detox initialization correctly for Android vs. iOS
- Add the `test_debug` profile to the EAS success hook for Android

### CODE REVIEW

File: e2e/tests/utils/openAppForDebugBuild.js [hunk 1]
```diff
@@ -6,16 +6,26 @@ module.exports.openAppForDebugBuild = async function openAppForDebugBuild() {
...
+    await device.launchApp();
+    sleep(1000);
+    await device.openURL({
+      url: deepLinkUrl,
+    });
+  } else {
+    await device.launchApp({
+      url: deepLinkUrl,
+    });
+  }
```
Comment (dsokal) [inline e2e/tests/utils/openAppForDebugBuild.js]: See https://github.com/expo/eas-tests-example/blob/main/e2e/tests/homeScreen.e2e.js#L5
`device.launchApp` will be called twice for debug builds. I don't think this is intended.

**Review by dsokal — CHANGES_REQUESTED** [review]

File: e2e/tests/utils/openAppForDebugBuild.js (hunk 1 above)
Comment (douglowder) [reply e2e/tests/utils/openAppForDebugBuild.js]: I've refactored the utils to launch the app correctly for both release and debug cases.

File: .detoxrc.json [hunk 2]
```diff
@@ -28,7 +28,7 @@
     "simulator": {
       "type": "ios.simulator",
       "device": {
-        "type": "iPhone 11"
+        "type": "iPhone 14"
```
Comment (douglowder) [inline .detoxrc.json:31]: I found that this was needed in order for tests to work on EAS, otherwise there is a `no such simulator` error from `applesimutils`.

**Review by dsokal — APPROVED** [review]
Looks good, thanks!
Can you, before merging this PR, put up a PR with the changes to https://docs.expo.dev/build-reference/e2e-tests/? You'll need to read the whole document and update the parts that were changed here.
These should be merged at the same time.
